// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Topugema.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250613224108_attachments2")]
    partial class attachments2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Counter", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Counters");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Channel_ID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("User_ID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("attachment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Channel_ID");

                    b.HasIndex("Channel_ID", "ID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Server", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("ServerSubscribe", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Server_ID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("User_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Server_ID");

                    b.HasIndex("User_ID");

                    b.HasIndex("User_ID", "Server_ID")
                        .IsUnique();

                    b.ToTable("ServerSubscribes");
                });

            modelBuilder.Entity("TextChannel", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Server_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Server_ID");

                    b.ToTable("TextChannels");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("verifed")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
